version: "3"
services: 
  fastapi:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    env_file:
      - ./.env

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_ddb
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: